### ISSUE TITLE
Collect Elasticsearch diagnostics of a given cluster using ECK diagnostics

### ISSUE THREAD

**Issue by gadekishore** [elastic/eck-diagnostics#121] opened 2022-08-26 18:44 UTC
It helps if we can add feature to collect specific deployment diagnostics using ECK diagnostics instead of collecting all deployments diagnostics data.

**Comment by thbkrkr** [comment] 2022-09-05 10:48
We should be able to do something but I would like to understand what's the problem that we want to solve here? Why is it a problem to collecting all deployments diagnostics data? Does it take too long? Is it generated a very large zip archive?
Do you know which part of the collected data is problematic? Is it k8s resources, k8s pod logs or stack diagnostics?

Some resources collected are not linked to a deployment but for others, we could add a level of filtering. I can imagine a new flag to specify the type and the name to target a specific deployment: 
`eck-diagnostics --filter type=elasticsearch,name=prod-region8-a42`.

Then it shoud be pretty easy to filter the following k8s objects: statefulsets, replicasets, controllerrevisions,  deployments, daemonsets, pods, persistentvolumeclaims, services, endpoints, configmaps, secrets and pod logs because we have labels `common.k8s.elastic.co/type` and `xxx.k8s.elastic.co/name` in place.
I would continue to collect all persistent volumes, network policies, service accounts, and most importantly all events.

List of data collected:
```
 <-- for the resources we would filter

# Cluster level
version
get nodes
get podsecuritypolicies
get storageclasses
describe clusterroles
describe clusterrolebindings

# Operator namespace
statefulsets
pods
services
configmaps
events
networkpolicies
controllerrevisions
serviceaccount

# Resource namespaces
get elasticsearch
get kibana
get apmserver
get enterprisesearch
get beat
get agent
get elasticmapsserver

get statefulsets <--
get replicasets <--
get controllerrevisions <--
get deployments <--
get daemonsets <--
get pods <--
get persistentvolumeclaims <--
get services <--
get endpoints <--
get configmaps <--
get secrets # meta only <--
logs <--

get persistentvolumes
get events
get networkpolicies
get serviceaccount

stack-diagnostic elasticsearch
stack-diagnostic kibana
stack-diagnostic agent
```

**Comment by thbkrkr** [comment] 2022-09-05 18:50
Duplicate of #81.

**Closed** 2022-11-17 17:35 UTC
Labels: enhancement
